/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package kr.sgm.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 3;
  /** RegularExpression Id. */
  int SEMICOLON = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int CHAR_STRING = 6;
  /** RegularExpression Id. */
  int INT_VALUE = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int SIGN = 9;
  /** RegularExpression Id. */
  int DATE_VALUE = 10;
  /** RegularExpression Id. */
  int NNNN = 11;
  /** RegularExpression Id. */
  int NN = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int ALPHABET = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"exit\"",
    "\";\"",
    "<EOL>",
    "<CHAR_STRING>",
    "<INT_VALUE>",
    "<DIGIT>",
    "<SIGN>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "<QUOTE>",
    "<ALPHABET>",
  };

}
